#include "descent.h"

ulong descent_side_run(two_cover_t cover, const descent_side *S,
                       int do_second_descent, slong max_descendants)
{
    fmpz_t d1, d2, z1, z2, z3, tmp, tmp2;
    fmpz_t T[3];
    fmpz_tqf_t tqf, tqf_red;
    qfb_t q1, q2, q3;
    bkf_t C;
    ulong nb, j, ncand;
    slong k;
    int d1_neg;

    fmpz_init(d1); fmpz_init(d2);
    fmpz_init(z1); fmpz_init(z2); fmpz_init(z3);
    fmpz_init(tmp); fmpz_init(tmp2);
    fmpz_init(T[0]); fmpz_init(T[1]); fmpz_init(T[2]);
    fmpz_tqf_init(tqf);
    fmpz_tqf_init(tqf_red);
    qfb_init(q1); qfb_init(q2); qfb_init(q3);
    bkf_init(C);

    // The ternary form is  -x'^2 + 4 d1 y^2 + delta z^2 = 0, obtained from
    // y^2 = d1 x^2 + c xz + d2 z^2 by completing the square (x' = 2 d1 x + c z).
    // Coefficients 0 and 2 do not depend on d1.
    tqf->coeffs[0]->sign = -1;
    tqf->coeffs[0]->num = 0;
    fmpz_factor_set(tqf->coeffs[2], S->deltaf);
    _fmpz_factor_fit_length(tqf->coeffs[1], 1 + S->df->num);

    // d1 runs over ALL square-free divisors of d, both signs: the image of the
    // connecting map lies in the subgroup of Q*/(Q*)^2 generated by the divisors
    // of d, and -1 is one of those whenever d < 0.
    ncand = 2 * (UWORD(1) << S->df->num);
    flint_printf("\n--- %s : %wu candidates for d1 ---\n", S->label, ncand);

    nb = 0;

    for (d1_neg = 0; d1_neg < 2; d1_neg++)
    for (j = 0; j < (UWORD(1) << S->df->num); j++)
    {
        fmpz_set_ui(d1, 1);
        for (k = 0; k < S->df->num; k++)
        {
            if (j & (UWORD(1) << k))
            {
                fmpz_mul(d1, d1, S->df->p + k);
            }
        }
        if (d1_neg)
        {
            fmpz_neg(d1, d1);
        }

        fmpz_divexact(d2, S->d, d1);
        bkf_set_2iso(C, d1, S->c, d2);

        if (!bkf_everywhere_local_solubility_2isogeny(C, S->c, S->d, S->delta, d1, S->p_all))
        {
            continue;
        }

        nb++;

        flint_printf("  [ELS] d1 = ");
        fmpz_print(d1);
        flint_printf("   C = ");
        bkf_print_magma(C);
        flint_printf("\n");

        if (fmpz_is_one(d1))
        {
            if (S->add_trivial)
            {
                add_cover_2isogeny(cover, d1, S->c, d2, S->x0, S->mtype_first);
            }
            else
            {
                flint_printf("       trivial class, no descent needed\n");
            }
            continue;
        }

        if (!do_second_descent)
        {
            add_cover_2isogeny(cover, d1, S->c, d2, S->x0, S->mtype_first);
            continue;
        }

        // second descent: first solve the conic of C, then split over d3
        // coefficient 1 is 4 d1, built from the same subset of primes as d1
        tqf->coeffs[1]->num = 1;
        fmpz_set_ui(tqf->coeffs[1]->p, 2);
        tqf->coeffs[1]->exp[0] = 2;
        tqf->coeffs[1]->sign = d1_neg ? -1 : 1;

        if (S->df->num != 0)
        {
            k = 0;
            if ((j & 1) && (fmpz_cmp_ui(S->df->p, 2) == 0))
            {
                tqf->coeffs[1]->exp[0]++;
                k++;   // 2 is already accounted for
            }

            for (; k < S->df->num; k++)
            {
                if (j & (UWORD(1) << k))
                {
                    fmpz_set(tqf->coeffs[1]->p + tqf->coeffs[1]->num, S->df->p + k);
                    tqf->coeffs[1]->exp[tqf->coeffs[1]->num] = 1;
                    tqf->coeffs[1]->num++;
                }
            }
        }

        fmpz_tqf_reduce(tqf_red, tqf, T);

        if (fmpz_tqf_solve_reduced(tqf_red, z1, z2, z3) != 1)
        {
            // Could not solve the conic, keep first descent and be sad.
            flint_printf("       conic unsolved, keeping the first descent cover\n");
            add_cover_2isogeny(cover, d1, S->c, d2, S->x0, S->mtype_first);
            continue;
        }

        // undo the reduction, then diagonal -> semi diagonal
        fmpz_mul(z1, z1, T[0]);
        fmpz_mul(z2, z2, T[1]);
        fmpz_mul(z3, z3, T[2]);

        fmpz_submul(z1, S->c, z3);
        fmpz_mul(z2, z2, d1);
        fmpz_mul_2exp(z2, z2, 1);
        fmpz_mul(z3, z3, d1);
        fmpz_mul_2exp(z3, z3, 1);

        fmpz_gcd3(tmp, z1, z2, z3);
        fmpz_divexact(z1, z1, tmp);
        fmpz_divexact(z2, z2, tmp);
        fmpz_divexact(z3, z3, tmp);

        // z2^2 == d1 z1^2 + c z1 z3 + d2 z3^2 : this must hold for both sides,
        // and used to be checked on only one of them
        fmpz_mul(tmp, z1, z1);
        fmpz_mul(tmp, tmp, d1);
        fmpz_mul(tmp2, z1, z3);
        fmpz_mul(tmp2, tmp2, S->c);
        fmpz_add(tmp, tmp, tmp2);
        fmpz_mul(tmp2, z3, z3);
        fmpz_mul(tmp2, tmp2, d2);
        fmpz_add(tmp, tmp, tmp2);
        fmpz_mul(tmp2, z2, z2);

        if (!fmpz_equal(tmp, tmp2))
        {
            flint_printf("Conic solution does not satisfy its own equation, aborting...\n");
            flint_abort();
        }

        fmpz_tqf_parametrize_semi_diag(q1, q2, q3, d1, S->c, d2, S->delta, z1, z2, z3);

        if (second_descent_d3(cover, d1, S->c, d2, S->x0, q1, q2, q3,
                              S->deltaf, S->p_all, S->mtype_second,
                              max_descendants) == 0)
        {
            flint_printf("       no ELS descendant => C(Q) is empty\n");
        }
    }

    flint_printf("  %s : %wu of %wu candidates everywhere locally soluble\n",
                 S->label, nb, ncand);

    fmpz_clear(d1); fmpz_clear(d2);
    fmpz_clear(z1); fmpz_clear(z2); fmpz_clear(z3);
    fmpz_clear(tmp); fmpz_clear(tmp2);
    fmpz_clear(T[0]); fmpz_clear(T[1]); fmpz_clear(T[2]);
    fmpz_tqf_clear(tqf);
    fmpz_tqf_clear(tqf_red);
    qfb_clear(q1); qfb_clear(q2); qfb_clear(q3);
    bkf_clear(C);

    return nb;
}
